"use strict";

import React from 'react';

const FacultyIcon = (props) => (
    <img
        {...props}
        src="data:img/png;base64,iVBORw0KGgoAAAANSUhEUgAAABYAAAAYCAMAAADJYP15AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAA6lBMVEXrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlnrvlkAAACOZUzgAAAATHRSTlMAV/l9/vv4gKTzKh3sqgLI4xl6ihbYzgYQye31ErTnJvKjc2KMiDFF+nlQOJdh/VJqDvchix+ns+udwra73pS4meHVx9uoCAQsXHHakyp/TgAAAAFiS0dETYBoIGUAAAAJcEhZcwAACxIAAAsSAdLdfvwAAAAHdElNRQfhDBMQKzWqde3NAAAAzElEQVQoz9WP61KCUBSFN7TRLFMghBQL0ewiSopaJF2sTE3X+z+PBxqmQl6g78c+a76ZfdZsohRJliXa44CVAhez9hClo+MyTv7IShWqpp8aNZjWjz1TUbcagN08x4WRWqcFl9rQO7ikLuyrb3t9w7eiEj0PfaKBr9zFdsjJOwoAZSyCF7BONEm3pvcPThK0EI/EmEUZnnwmlQEW/BrgZ7H0grgBosBDfCa/Jn/9Uz1/gzj4HWYUfWAhIsLPJa0U3sNf05ebw4a2yCHcAc3iNdRCNAzqAAAAAElFTkSuQmCC"
    />
);

export default FacultyIcon;
